# Generated by Django 4.1.3 on 2022-11-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='update_date',
        ),
    ]
