# Generated by Django 4.1.3 on 2022-11-25 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_following_following_no_follow_twice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_likes',
        ),
    ]
